-- Tabelas adicionais para compatibilidade serverless/Vercel.
-- Execute no SQL Editor do Supabase do projeto usado pelo backend.

create table if not exists app_settings (
  id text primary key default 'default',
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists radar_excluded_groups (
  group_id text primary key,
  created_at timestamptz not null default now()
);

create table if not exists alert_correlations (
  channel text not null,
  message_id text not null,
  lead_id text,
  kind text not null,
  created_at timestamptz not null default now(),
  primary key (channel, message_id)
);

create table if not exists dashboard_events (
  id bigint generated by default as identity primary key,
  type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists dashboard_events_created_at_idx
  on dashboard_events (created_at);
